basestation:
  node-type: "base_station"
  IP-address: "127.0.0.1"
  using-radio: "brick-1"
  base-port: "1234"
  clients:
    - "none_iris"
    - "jackal"


jackal:
  node-type: "ground_robot"
  IP-address: "127.0.0.1"          
  using-radio: "radio_ugv"
  base-port: "2234"
  clients:
    - "none_iris"
    - "basestation"

none_iris:
  node-type: "aerial_robot"
  IP-address: "127.0.0.1"
  using-radio: "radio_uav"
  base-port: "6234"
  clients:
    - "jackal"
    - "basestation"